# Importing libraries

In [493]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Dataset

In [494]:
df=pd.read_csv("Accidents_Data.csv",low_memory=False)
df

INATTENTIONIND UNDERINFL   WEATHER ROADCOND                LIGHTCOND  \
0                 NaN         N  Overcast      Wet                 Daylight   
1                 NaN         0   Raining      Wet  Dark - Street Lights On   
2                 NaN         0  Overcast      Dry                 Daylight   
3                 NaN         N     Clear      Dry                 Daylight   
4                 NaN         0   Raining      Wet                 Daylight   
...               ...       ...       ...      ...                      ...   
194668            NaN         N     Clear      Dry                 Daylight   
194669              Y         N   Raining      Wet                 Daylight   
194670            NaN         N     Clear      Dry                 Daylight   
194671            NaN         N     Clear      Dry                     Dusk   
194672            NaN         N     Clear      Wet                 Daylight   

       SPEEDING  SEVERITYCODE  
0           NaN             2  
1           NaN             1  
2           NaN             1  
3           NaN             1  
4           NaN             2  
...         ...           ...  
194668      NaN             2  
194669      NaN             1  
194670      NaN             2  
194671      NaN             2  
194672      NaN             1  

[194673 rows x 7 columns]

In [495]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194673 entries, 0 to 194672
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype 
---  ------          --------------   ----- 
 0   INATTENTIONIND  29805 non-null   object
 1   UNDERINFL       189789 non-null  object
 2   WEATHER         189592 non-null  object
 3   ROADCOND        189661 non-null  object
 4   LIGHTCOND       189503 non-null  object
 5   SPEEDING        9333 non-null    object
 6   SEVERITYCODE    194673 non-null  int64 
dtypes: int64(1), object(6)
memory usage: 10.4+ MB


In [496]:
df.isnull().sum()

INATTENTIONIND    164868
UNDERINFL           4884
WEATHER             5081
ROADCOND            5012
LIGHTCOND           5170
SPEEDING          185340
SEVERITYCODE           0
dtype: int64

In [497]:
df.columns

Index(['INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'SPEEDING', 'SEVERITYCODE'],
      dtype='object')

# Converting Severity Code from 1 and 2 To 0 and 1

In [498]:
severity_code = df['SEVERITYCODE'].values

In [499]:
from sklearn import preprocessing
labels = preprocessing.LabelEncoder()
labels.fit([1, 2])
severity_code = labels.transform (severity_code)

In [500]:
df["SEVERITYCODE"] = severity_code

In [501]:
df["SEVERITYCODE"].unique()

array([1, 0], dtype=int64)

## encoding la colonne  attention ("INATTENTIONIND") par  (0 = No, 1 = Yes)

In [502]:
df["INATTENTIONIND"].unique()

array([nan, 'Y'], dtype=object)

In [503]:
df["INATTENTIONIND"].replace("Y", 1, inplace=True)
df["INATTENTIONIND"].replace(np.nan, 0, inplace=True)

In [504]:
df["INATTENTIONIND"].unique()

array([0., 1.])

In [505]:
df["INATTENTIONIND"] = df["INATTENTIONIND"].astype('int')

In [506]:
df["INATTENTIONIND"].unique()

array([0, 1])

## encoding Sous l'influence ("UNDERINFL") par (0 = No, 1 = Yes)

In [507]:
df["UNDERINFL"].unique()

array(['N', '0', nan, '1', 'Y'], dtype=object)

In [508]:
df["UNDERINFL"].replace("N", 0, inplace=True)
df["UNDERINFL"].replace("Y", 1, inplace=True)

In [513]:
df["UNDERINFL"].fillna(df["UNDERINFL"].mode()[0], inplace=True)

In [514]:
df["UNDERINFL"].unique()

array([0, '0', '1', 1], dtype=object)

In [515]:
df["UNDERINFL"] = df["UNDERINFL"].astype('int')

In [516]:
df["UNDERINFL"].unique()

array([0, 1])

## encoding la vitesse ("Speeding") par (0 = No, 1 = Yes)

In [522]:
df["SPEEDING"].unique()

array([0, 1])

In [523]:
df["SPEEDING"].replace("Y", 1, inplace=True)
df["SPEEDING"].replace(np.nan, 0, inplace=True)

In [524]:
df["SPEEDING"].unique()

array([0, 1])

In [525]:
df["SPEEDING"] = df["SPEEDING"].astype('int')

In [526]:
df["SPEEDING"].unique()

array([0, 1])

## Encoding Light Conditions ("LIGHTCND") par (0 = Light, 1 = Medium, 2 = Dark)

In [527]:
df["LIGHTCOND"].unique()

array(['Daylight', 'Dark - Street Lights On', 'Dark - No Street Lights',
       nan, 'Unknown', 'Dusk', 'Dawn', 'Dark - Street Lights Off',
       'Other', 'Dark - Unknown Lighting'], dtype=object)

In [528]:
df["LIGHTCOND"].replace("Daylight", 0, inplace=True)
df["LIGHTCOND"].replace("Dark - Street Lights On", 1, inplace=True)
df["LIGHTCOND"].replace("Dark - No Street Lights", 2, inplace=True)
df["LIGHTCOND"].replace("Dusk", 1, inplace=True)
df["LIGHTCOND"].replace("Dawn", 1, inplace=True)
df["LIGHTCOND"].replace("Dark - Street Lights Off", 2, inplace=True)
df["LIGHTCOND"].replace("Dark - Unknown Lighting", 2, inplace=True)
df["LIGHTCOND"].replace("Other","nan", inplace=True)
df["LIGHTCOND"].replace('Unknown',"nan", inplace=True)

In [529]:
df["LIGHTCOND"].unique()

array([0, 1, 2, nan, 'nan'], dtype=object)

In [531]:
df["LIGHTCOND"].fillna(df["LIGHTCOND"].mode()[0], inplace=True)

In [532]:
df.drop(df.loc[df["LIGHTCOND"]=='nan'].index, inplace=True)

In [533]:
df["LIGHTCOND"].unique()

array([0, 1, 2], dtype=int64)

## Encoding "ROAD CONDITION" par (0 = Dry, 1 = Mushy, 2 = Wet)

In [565]:
df["ROADCOND"].unique()

array([2, 0, nan, 1], dtype=object)

In [566]:
df["ROADCOND"].replace("Dry", 0, inplace=True)
df["ROADCOND"].replace("Wet", 2, inplace=True)
df["ROADCOND"].replace("Ice", 2, inplace=True)
df["ROADCOND"].replace("Snow/Slush", 1, inplace=True)

df["ROADCOND"].replace("Standing Water", 2, inplace=True)
df["ROADCOND"].replace("Sand/Mud/Dirt", 1, inplace=True)
df["ROADCOND"].replace("Oil", 2, inplace=True)
df["ROADCOND"].replace("Other", "nan", inplace=True)
df["ROADCOND"].replace("Unknown", "nan", inplace=True)


In [567]:
df["ROADCOND"].unique()

array([2, 0, nan, 1], dtype=object)

In [568]:
df["ROADCOND"].value_counts()

0    122403
2     48084
1       934
Name: ROADCOND, dtype: int64

In [572]:
df["ROADCOND"].fillna(df["ROADCOND"].mode()[0], inplace=True)

In [573]:
df.drop(df.loc[df["ROADCOND"]=='nan'].index, inplace=True)

In [574]:
df["ROADCOND"].unique()

array([2, 0, 1], dtype=int64)

## Encoding "Weather Conditions" par (0 = Clear, 1 = Overcast and Cloudy, 2 = Windy, 3 = Rain and Snow 

In [575]:
df["WEATHER"].unique()

array(['Overcast', 'Raining', 'Clear', nan, 'Unknown', 'Snowing', 'Other',
       'Fog/Smog/Smoke', 'Sleet/Hail/Freezing Rain', 'Blowing Sand/Dirt',
       'Severe Crosswind', 'Partly Cloudy'], dtype=object)

In [576]:
df["WEATHER"].replace("Clear", 0, inplace=True)
df["WEATHER"].replace("Raining", 3, inplace=True)
df["WEATHER"].replace("Overcast", 1, inplace=True)

df["WEATHER"].replace("Snowing", 3, inplace=True)
df["WEATHER"].replace("Fog/Smog/Smoke", 2, inplace=True)
df["WEATHER"].replace("Sleet/Hail/Freezing Rain", 3, inplace=True)
df["WEATHER"].replace("Blowing Sand/Dirt", 2, inplace=True)
df["WEATHER"].replace("Severe Crosswind", 2, inplace=True)
df["WEATHER"].replace("Partly Cloudy", 1, inplace=True)
df["WEATHER"].replace("Other", "nan", inplace=True)
df["WEATHER"].replace("Unknown", 'nan' , inplace=True)

In [577]:
df["WEATHER"].unique()

array([1, 3, 0, nan, 'nan', 2], dtype=object)

In [578]:
df["WEATHER"].fillna(df["WEATHER"].mode()[0], inplace=True)

In [579]:
df.drop(df.loc[df["WEATHER"]=='nan'].index, inplace=True)

In [580]:
df["WEATHER"].unique()

array([1, 3, 0, 2], dtype=object)

In [581]:
df.isnull().sum()

INATTENTIONIND    0
UNDERINFL         0
WEATHER           0
ROADCOND          0
LIGHTCOND         0
SPEEDING          0
SEVERITYCODE      0
dtype: int64

# Application des algorithmes de machine learning  

In [587]:
X=df[["SPEEDING","INATTENTIONIND","UNDERINFL","ROADCOND","WEATHER","LIGHTCOND"]].values
y=df[["SEVERITYCODE"]].values

## Test/Train split

In [588]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print ('Train shape:', X_train.shape,  y_train.shape)
print ('Test shape:', X_test.shape,  y_test.shape)

Train shape: (122651, 6) (122651, 1)
Test shape: (52565, 6) (52565, 1)


# Modelling Algorithm(KNN)

In [589]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors =7,metric = 'euclidean')
classifier.fit(X_train, y_train.ravel())

KNeighborsClassifier(metric='euclidean', n_neighbors=7)

In [590]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [591]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
print("------------------------------------------------------")
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
print('------------------------------------------------------')
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)


Confusion Matrix:
[[33289  2343]
 [15636  1297]]
------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.93      0.79     35632
           1       0.36      0.08      0.13     16933

    accuracy                           0.66     52565
   macro avg       0.52      0.51      0.46     52565
weighted avg       0.58      0.66      0.57     52565

------------------------------------------------------
Accuracy: 0.6579663274041663


## appliying GridSearchCV for the KNN MODEL

In [476]:
from sklearn.model_selection import  GridSearchCV
import numpy as np

k_range = list(range(1, 10,2))
print(k_range)

[1, 3, 5, 7, 9]


In [477]:
param_grid = dict(n_neighbors=k_range)
print(param_grid)

{'n_neighbors': [1, 3, 5, 7, 9]}


In [592]:
grid = GridSearchCV(classifier, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(X_train, y_train.ravel())

GridSearchCV(cv=10,
             estimator=KNeighborsClassifier(metric='euclidean', n_neighbors=7),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9]}, scoring='accuracy')

In [593]:
grid_mean_scores = grid.cv_results_['mean_test_score']
print(grid_mean_scores)

[0.6012583  0.52182087 0.53843726 0.5414132  0.54301121]


In [594]:
grid.best_score_

0.601258295445655

In [595]:
#best paramètre pour K
grid.best_params_

{'n_neighbors': 1}

# Random Forests Classifiers

In [596]:
from sklearn.ensemble import RandomForestClassifier

#cree le modele de RandomForestClassifier 
clf=RandomForestClassifier(n_estimators=1000)

#Train le modele 
clf.fit(X_train,y_train.ravel())

y_predR=clf.predict(X_test)

In [597]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_predR))
print(classification_report(y_test,y_predR))
accuracy_score_RFC=accuracy_score(y_test, y_predR)
print(accuracy_score_RFC)

[[35495   137]
 [16833   100]]
              precision    recall  f1-score   support

           0       0.68      1.00      0.81     35632
           1       0.42      0.01      0.01     16933

    accuracy                           0.68     52565
   macro avg       0.55      0.50      0.41     52565
weighted avg       0.60      0.68      0.55     52565

0.6771616094359365


# Saving the model as PKL file 

In [470]:
import pickle
data = {"model": clf , "Précision": accuracy_score_RFC}
with open('Modelfinal.pkl', 'wb') as file:
    pickle.dump(data, file)

In [ ]:
#tester le modele (  une exemple de valeur [0,1,1,0,1,2] )
x=np.array([[0,1,1,0,1,2]])
y_pre=clf.predict(x)
y_pre

In [473]:
#testing le fichier PKL 
with open('Modelfinal.pkl', 'rb') as file:
    data = pickle.load(file)
rp=data['model']
y_pre1 = rp.predict(x)
y_pre1

array([0], dtype=int64)